### ISSUE TITLE
README.md doesn't list libcapstone-dev or flex/bison dependency

### ISSUE THREAD

**Issue by pcordes** [SimonKagstrom/emilpro#30] opened 2015-08-01 21:08 UTC
I'm building emilpro for the first time on Ubuntu 15.04.

Besides the listed libraries, I had to install libcapstone-dev, and flex/bison.  (I was surprised that flex/bison aren't pulled in by Debian/Ubuntu's build-essential dependency-package, but they're not.)

Also, I was hoping it could use binutils-dev instead of building its own copy, but it just does what the docs say and builds its own.  And unfortunately doesn't pass along the -j4 make option, so it's building binutils single-threaded.

**Comment by SimonKagstrom** [comment] 2015-08-02 14:07
I'll update the README.md some day - the capstone dependency is new, but should be optional anyhow (it's still a bit work in progress).

As for the binutils dependency, it's tracked via Issue #7. Basically, the problem is that in Debian/Ubuntu (at least until 14.04), binutils-dev was only available for single-architecture binutils - in EmilPRO, I think the multi-architecture support is more or less a must - thus it builds binutils as part of the build process.

**Comment by SimonKagstrom** [comment] 2015-08-09 06:12
Fixed with c627527

**Closed by SimonKagstrom** 2015-08-09 06:12 UTC
