### ISSUE TITLE
make fails with undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by ALTree** [SimonKagstrom/emilpro#27] opened 2015-06-11 20:28 UTC
```
$ uname -a

Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

`gcc (Debian 4.9.2-16) 4.9.2`

```
$ make
[  8%] Built target binutils
[  8%] Built target file-to-source
Linking CXX executable emilpro
/usr/bin/ld: CMakeFiles/emilpro.dir/src/model.cc.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/emilpro.dir/build.make:680: recipe for target 'emilpro' failed
make[2]: *** [emilpro] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/emilpro.dir/all' failed
make[1]: *** [CMakeFiles/emilpro.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by SimonKagstrom** [comment] 2015-06-12 06:49
Can't reproduce this, but I did a chance commit (18569c6) which perhaps fixes it.

Can you update and test this when you have the time?

**Comment by ALTree** [comment] 2015-06-12 12:50
I should have mentioned that I got that error whit the .tar.gz at www.emilpro.com/ (I don't know how updated it is).

I just tried with the git repo @  commit 18569c6 and I got a brand new error:

```
checking for bison... /home/alberto/Desktop/emilpro/build/binutils/missing bison -y
checking for flex... /home/alberto/Desktop/emilpro/build/binutils/missing flex
checking lex output file root... configure: error: cannot find output from /home/alberto/Desktop/emilpro/build/binutils/missing flex; giving up
```

I instelled flex, got a bison error, I installed bison, and that fixed it.

**Comment by SimonKagstrom** [comment] 2015-06-12 18:01
OK, good.

There have been many changes since the last proper release on www.emilpro.com, but they are mostly of the Qt port of the disassembler. Anyway, I'm closing this report since the commit above seems to have resolved the linking problem.

**Closed by SimonKagstrom** 2015-06-12 18:01 UTC
